# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run.
on:
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - uses: Azure/k8s-set-context@v1
        name: Connect to Kubernetes
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          context: cloud_okteto_com

      - uses: Azure/k8s-deploy@v1.3
        with:
          manifests: |
            kubernetes/api.yaml
            kubernetes/database.yaml
          namespace: pmorelli92
