# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-db:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - uses: pmorelli92/github-container-registry-build-push@1.0.2
        name: Build and publish latest database image
        with:
          # Read note below to see how to generate the PAT
          personal-access-token: ${{secrets.GHCR_PAT}}
          docker-image-name: postgres-digimon-3ds
          docker-image-tag: latest
          dockerfile-path: ./src/database/Dockerfile
          build-context: ./src/database

  build-app:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - uses: pmorelli92/github-container-registry-build-push@1.0.2
        name: Build and Publish latest api image
        with:
          # Read note below to see how to generate the PAT
          personal-access-token: ${{secrets.GHCR_PAT}}
          docker-image-name: api-digimon-3ds
          docker-image-tag: latest
          dockerfile-path: ./src/api/Dockerfile
          build-context: ./src/api
